service: SESApi

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - ses:CreateTemplate
        - ses:SendTemplateEmail
        - ses:DeleteTemplate
      Resource: "*"

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello

  sendEmail:
    handler: handlers/sendEmail.sendEmail
    events:
      - httpApi:
          path: /emailSES/sendEmail/{ToEmail}/{Code}
          method: get

  sendEmailParameters:
    handler: handlers/sendEmailParameters.sendEmailParameters
    events:
      - httpApi:
          path: /emailSES/sendEmailParameters
          method: post


